postgis/postgis

deps/ryu/Makefile.in

Libtool uses the default shell, and for dronie this seems to be
different than bash so it fails to understand the  syntax.
References #4543
Drone logs:
```
/bin/sh ../../libtool --mode=compile gcc -I..  -I/usr/local/include  -I/usr/local/include   -I/usr/include/libxml2  -I/usr/include/json-c    -DNDEBUG  -std=gnu99 -O2 -Wall -fno-omit-frame-pointer -Werror -fno-math-errno -fno-signed-zeros  -fPIC -DPIC -DRYU_NO_TRAILING_ZEROS -c -o d2fixed.lo d2fixed.c
--
535 | ../../libtool: 1: eval: base_compile+= gcc: not found
536 | ../../libtool: 1: eval: base_compile+= -I..: not found
537 | ../../libtool: 1: eval: base_compile+= -I/usr/local/include: not found
538 | ../../libtool: 1: eval: base_compile+= -I/usr/local/include: not found
539 | ../../libtool: 1: eval: base_compile+= …
```

Ryu Makefile: Include shell variable

---

doc/reference_raster.xml

Fix https://trac.osgeo.org/postgis/ticket/4786

Fix return type in doc of the ST_SetRotation function

---

configure.ac

In case of cross-compile AC_PROJ_VERSION([POSTGIS_PROJ_VERSION]) fails.
So try to get version by pkg-config first

Use pkg-config to get PROJ version if available

---

configure.ac

Try to retrieve the version from pkg-config to avoid the following error:
```
checking protobuf-c version... configure: error: in `/home/fabrice/buildroot/output/build/postgis-3.1.1':
configure: error: cannot run test program while cross compiling
```
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>

configure.ac: fix cross-compilation with protobuf-c

---

doc/using_postgis_dataman.xml
loader/shp2pgsql-cli.c
loader/shp2pgsql-core.c
loader/shp2pgsql-core.h
regress/loader/PointWithSchema.opts

Adding a new flag called -Z . When used, this flag will prevent the generation of ANALYZE statements. Without the -Z flag (default behaviour), the ANALYZE statements will be generated.

added -Z option to prevent tables from being  analyzed

---

liblwgeom/lwgeom_geos.c

Improves by 10% the performance of the following test query (time remains dominated by deserialization)
```
SELECT sum(ST_NPoints(geom)) FROM (SELECT postgis_geos_noop(geom) AS geom FROM gadm36_0) sq;
```

Improve performance of LWGEOM-GEOS conversion

---

postgis/geography_measurement.c

This fixes an obvious typo since `100 nm = 100e-9 m = 1/1.0e7 m`.  This
only affects `!defined(PROJ_GEODESIC)` code which may not be active any
more.
However, to go back to the ticket #2168 that generated this `INVMINDIST`
hack...
The `defined(PROJ_GEODESIC)` code for geodesics is guaranteed to be
symmetric in the calculation of distances, i.e., `dist(A,B) = dist(B,A)`.  So it
would be better to avoid quantizing the distance calculation to fix a
non-existent problem.
Of course the length of a line string make change if it's reversed (just
from the properties of floating point addition).  However the hack is
still ill-advised.  If covers up the problem it most cases, but would
exacerbate it in a small fraction of cases.
I'm not making this change myself, because I'm not a direct user of …

Fix typo in setting of INVMINDIST.

---

regress/run_test.pl

Reduces the noise on backend crashes, like:
https://github.com/postgis/postgis/runs/3123818054?check_suite_focus=true

Early exit if psql returns an error

---

configure.ac

Closes https://trac.osgeo.org/postgis/ticket/4955#ticket

Fix protobuf (non-)detection in the --without-protobuf case.

---

doc/reference_operator.xml
doc/reference_processing.xml
doc/reference_raster.xml
doc/reference_srs.xml
doc/reference_trajectory.xml
doc/reference_type.xml
doc/reference_version.xml
doc/reporting.xml
doc/using_postgis_dataman.xml
doc/using_postgis_query.xml
doc/using_raster_dataman.xml

One hyperlink with neighbour was not changed and release_notes.xml did not have behaviour changed.  NB many raster functions allow a NearestNeighbor (english or american spelling) parameter.  That note remains as is.

Adjusted spelling of Neighbor and Behavior

---

README.postgis

I recently rebooted some postgis development efforts that required me to get a fully debuggable dev environment up and running which was not straight forward. After much non existent hair pulling I now seem to have settled on taking advantage of the CI setup and make use of it locally. I've written this small section to explain why this is useful and a minimal set of instructions how to use it at a *nix host because I think it could be useful for others and myself next time I have forgotten everything.

Add section about debug requirements and tips

---

.github/workflows/ci.yml

In some cases it can be very useful to know the results of all architectures.

Avoid failed matrix run to cancel others

---

doc/reference_editor.xml

The ST_ShiftLongitude function behave symmetrical with inverse and reverse transformations. Clarify this in the docs.
resolves #5010
https://trac.osgeo.org/postgis/ticket/5010

Clarify ST_ShiftLongitude docs

---

doc/reference_output.xml

The `||` operator implies concatenation of one row, but in many cases each row represents a separate layer - thus better to mention `STRING_AGG` as an alternative, and help those less familiar with SQL.
P.S. I am not certain if I need to run some doc regeneration for other files in `/po` dir.

minor change to st_asmvt doc

---

doc/reference_output.xml

The function `ST_AsMVT` won't find the geometry column if an unquoted column identifier uses uppercase characters, as PostgreSQL automatically folds unquoted identifiers to lower case.
```sql
WITH j AS (
SELECT ST_AsMVTGeom(geom, ST_MakeBox2D(ST_Point(0, 0), ST_Point(4096,4096))) AS MVTGeom FROM t
)
SELECT ST_AsMVT(j,'foo',4096,'MVTGeom') FROM j;
ERROR:  parse_column_keys: no geometry column found
```
This documentation patch adds a hint and a link to PostgreSQL capitalization handling for unquoted identifiers.

Adds hint to postgres caps handling for unquoted identifiers

---

postgis/geography.sql.in
postgis/postgis.sql.in

https://www.postgresql.org/message-id/flat/CAJEAwVELVx9gYscpE%3DBe6iJxvdW5unZ_LkcAaVNSeOwvdwtD%3DA%40mail.gmail.com
Decompress support function has become optional in gist since Postgres 11. This PR removes decompress for all gist implementation because they all are NOP in PostGIS. Also I observe 4-6% faster scan and build like mentioned in pgsql-hackers discussion.

remove gist decompress support function

---

NEWS
raster/rt_pg/rtpg_mapalgebra.c

These changes improve performance of raster clip by "inlining" of `rt_raster_iterator`. Although `rt_raster_iterator` is very useful generic function that allows to merge several rasters but as I discovered it's pretty inefficient in terms of memory usage when it comes to simple case like clipping (for example several separate allocations for every pixel in a band is pretty crazy). With this change I see 1.3x-1.7x speed up for my input data.

Speed up RASTER_Clip

---

NEWS
raster/rt_core/rt_geometry.c

I would like to remove geometry validation from RT_ST_DumpAsPolygons and I see several reasons to do that:
- Removing GEOS validation and geometry fix calls makes RT_ST_DumpAsPolygons work 2.5x-3x faster for my data
- Since time this function was written GDAL seem to be improved and do better job at producing valid polygons
Also there will still be an option to call ST_MakeValid on output but performance of RT_ST_DumpAsPolygons itself will be better.

Remove GEOS geometry validation from RT_ST_DumpAsPolygons

---

extensions/address_standardizer/std_pg_hash.c

ci->lextab is tested 3 times. I guess it's a cut/paste mistake and
should be replaced by the two other variables ci->gaztab and ci->rultab.

std_pg_hash.c: fix cut/paste in IsInStdPortalCache

---

loader/Makefile.in

In case of shared libs build fails:
ld: cannot find -lgeos_c
ld: attempted static link of dynamic object `/usr/lib/libproj.so'

Disable forced static linking of liblwgeom

---

raster/loader/Makefile.in

This is similar to commit
https://github.com/postgis/postgis/commit/98070faad220e12fcaed9a583a70a37c510b7c6b,
but applied to raster/loader. It ensures that if only shared variants
of the libraries are available, the link still works. If you force
-static and only shared variants of some of the libraries are
available, the link fails with "d: attempted static link of dynamic
object XYZ".
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>

raster/loader/Makefile.in: do not force static linking

---

doc/reference_srs.xml
doc/using_postgis_dataman.xml
liblwgeom/liblwgeom.h.in
liblwgeom/lwgeom_transform.c
postgis/lwgeom_transform.c
postgis/postgis.sql.in
regress/core/regress_proj_pipeline.sql
regress/core/regress_proj_pipeline_expected
regress/core/tests.mk.in

As discussed in [Trac #5006](https://trac.osgeo.org/postgis/ticket/5006), add the ability to use a specific PROJ conversion pipeline instead of the automatically selected one via `ST_Transform()` (`proj_crs_to_crs()`).
Thanks to @rouault for all his help at the FOSS4G 2022 code sprint getting it working 😃  Commit messages should be relatively self-explanatory.
---
```SQL
geometry ST_TransformPipeline(geom geometry, pipeline text[, to_srid integer])
geometry ST_InverseTransformPipeline(geom geometry, pipeline text[, to_srid integer])
```
Transformation pipelines are defined using any of the following string formats:
- `urn:ogc:def:coordinateOperation:AUTHORITY::CODE`. Note that a simple `AUTHORITY:CODE` string does not uniquely identify a coordinate operation: the same code can be used for …

Add ST_TransformPipeline

---

liblwgeom/lwgeom.c
regress/core/quantize_coordinates.sql
regress/core/quantize_coordinates_expected

We can completely avoid any floating-point computation by directly using the fact that the IEEE-754 representation of a floating point number contains the integral part of log2(abs(number)).
The improved trim_preserve_decimal_digits() function is ~ 7x times faster.

ST_QuantizeCoordinates(): speed-up implementation

---

doc/Makefile.in
doc/postgis.xml
doc/reference.xml
doc/reference_coverage.xml
liblwgeom/lwgeom_geos.c
liblwgeom/lwgeom_topo.c
postgis/lwgeom_accum.c
postgis/lwgeom_geos.c
postgis/lwgeom_geos.h
postgis/lwgeom_window.c
postgis/postgis.sql.in
regress/core/coverage.sql
regress/core/coverage_expected
regress/core/tests.mk.in

Adds three new functions, 
* ST_CoverageIsValid(geom geometry winset, tolerance float8)
* ST_CoverageSimplify(geom geometry winset, tolerance float8, simplifyBoundary integer)
* ST_CoverageUnion(geom geometry set)
For the purpose of these functions a "coverage" is a set of polygons with perfectly shared edges (no overlaps or gaps and exact vertex matching).

Coverage Simplification, Validation, Union

---

liblwgeom/lwline.c

Changes "ordinate" to "coordinate"

lwline.c: fix a typo

---

liblwgeom/lwin_wkb.c

Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=65973

lwcurvepoly_from_wkb_state(): avoid potentially very deeply neested geometries causing stack call overflow

---

doc/reference_cluster.xml

The `k` argument was mis-named as `number_of_clusters` for the `K`-Means cluster function.
Passing named arguments with `number_of_clusters` failed, the correct syntax is:
```sql
SELECT id, ST_ClusterKMeans(geom, k => 10, max_radius => 1000), ...
```
This PR fixes the inaccurate name in the docs.

Fix KMeans parameter name

---

.cirrus.yml

Small "early year" update. I've rewritten the CI configurations with better step separation for clarity. I've attempted to apply some optimizations and improvements.
FreeBSD:
- Upgrade to FreeBSD 14.2
- Added ccache and cache configuration
- Optimized parallel builds
- Move pcre to pcre2
macOS:
- Update to macOS Sonoma
- Upgrade to PostgreSQL 17
- Add ccache and some flags
- Add with-topology and protobuf support

CI Update: FreeBSD 14.2 and macOS Sonoma

---

postgis/gserialized_estimate.c

I fixed a compilation issue related to an uninitialized variable. In our environment, this warning lead to an error.
Should I add the following switch 
-Wmaybe-uninitialized
to run_tests.sh / run_upgrade.sh

Remove uninitialized variable warning

---

extensions/address_standardizer/std_pg_hash.c

Bad copy paste was potential reason of NULL pointer dereference
Fixes: c6091a4bb ("Prep to move address_standardizer into extensions folder")

Fix NULL-pointer checks for gaztab and rultab in GetStdFromPortalCache

---

extensions/address_standardizer/standard.c

The memory was not released in case of error handling.
Found by PostgresPro with Svace static analyzer
Fixes: c6091a4bb ("Prep to move address_standardizer into extensions folder")

address_standardizer: fixed memory leak
